sudo: required
services:
  - docker

before_install:
  - docker build -t hrgrigorov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hrgrigorov/react-test npm test -- -- coverage

after_success:
  - docker build -t hrgrigorov/multi-client ./client
  - docker build -t hrgrigorov/multi-nginx ./nginx
  - docker build -t hrgrigorov/multi-server ./server
  - docker build -t hrgrigorov/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push hrgrigorov/multi-client
  - docker push hrgrigorov/multi-nginx
  - docker push hrgrigorov/multi-server
  - docker push hrgrigorov/multi-worker
